name: Rust

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Format
      run: cargo fmt --check --verbose
    - name: Clippy
      run: cargo clippy -- -D warnings
    - name: Build for x86_64
      run: cargo build --release --verbose
